backup-sd: Streaming SD card backup bt-daeomon: Bugfix failed bind logrotate: Reduce config files

diff --git a/sbin/backup-sd b/sbin/backup-sd
--- a/sbin/backup-sd
+++ b/sbin/backup-sd
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Backup SD card image to external HDD
+# Backup SD card image to a remote SSH host
 # Must run as root
 #
 # This source file is part of the follwoing repository:
@@ -10,7 +10,7 @@
 #   http://www.microfarad.de
 #   http://www.github.com/microfarad-de
 #
-# Copyright (C) 2019 Karim Hraibi (khraibi@gmail.com)
+# Copyright (C) 2025 Karim Hraibi (khraibi@gmail.com)
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -26,20 +26,21 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 
+set -euo pipefail
+
 # Path to the current directory where this script is located
-DIR=$(dirname $(readlink -f "$BASH_SOURCE"))
+SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
 
 # Include common configuration file
-source "$DIR/common.sh"
-
+# shellcheck source=/dev/null
+source "$SCRIPT_DIR/common.sh"
 
 # Configuration parameters
-OUTDIR="$CFG_BACKUP_SD_DESTINATION"
 DEVICE="$CFG_BACKUP_SD_DEVICE"
-OUTFILE="sd_card.img"
+SSH_HOST="$CFG_BACKUP_SD_DEST_SSH"
+DEST_DIR="$CFG_BACKUP_SD_DEST_DIR"
 LOCK="$CFG_TMPFS_DIR/backup-sd.lock"
 LOG="$CFG_LOG_DIR/backup-sd.log"
-
 
 function infoLog {
   _infoLog "$1" "backup-sd" "$LOG" "ecd"
@@ -51,62 +52,47 @@ function warningLog {
 
 function errorLog {
   _errorLog "$1" "backup-sd" "$LOG" "ecd"
-  semaphoreRelease "$LOCK"
-  exit 1
 }
-
 
 ################
 #### START  ####
 ################
 
+# Always release lock on exit (success or failure)
+cleanup() {
+  semaphoreRelease "$LOCK" >/dev/null 2>&1 || true
+}
+trap cleanup EXIT
+
+# Convert any command error into a logged error
+trap 'rc=$?; errorLog "backup failed ($rc)"' ERR
+
 # avoid multiple instances of this script
-semaphoreLock "$LOCK"
+semaphoreLock "$LOCK" " "
 if [[ $? -ne 0 ]]; then
   warningLog "an instance of the current script is already running (please remove $LOCK)"
   exit 1
 fi
 
-install -d "$OUTDIR"
-rv=$?
-if [[ $rv -ne 0 ]]; then
-  errorLog "failed to create $OUTDIR (exit code $rv)"
+HOST="$(hostname -s)"
+TS="$(date -u +%Y%m%d-%H%M%S)"
+FILE="$HOST-$TS-sd.img"
+REMOTE_OUT="$DEST_DIR/$FILE.zst"
+REMOTE_TMP="$REMOTE_OUT.partial"
+
+# Flush pending writes if available (don’t fail if blockdev isn’t present)
+if command -v blockdev >/dev/null 2>&1; then
+  blockdev --flushbufs "$DEVICE" || true
 fi
 
-# Read disk image and split into chunks
-dd if="$DEVICE" of="$OUTDIR/$OUTFILE" bs=4M status=progress
-rv=${PIPESTATUS[0]}
-if [[ $rv -eq 0 ]]; then
-  infoLog "$DEVICE backed-up to $OUTDIR"
-else
-  errorLog "failed to back-up $DEVICE (exit code $rv)"
-fi
+# Stream: SD -> zstd (local compression) -> ssh (remote store), atomic on remote
+dd if="$DEVICE" bs=4M \
+| zstd -T0 -3 -v \
+| ssh "$SSH_HOST" "cat > '$REMOTE_TMP' && mv -f '$REMOTE_TMP' '$REMOTE_OUT'"
 
-for path in "${CFG_BACKUP_SD_AUX_DIR[@]}"; do
-  install -d "$OUTDIR/$path"
-  rsync -avu --delete "$path/" "$OUTDIR/$path/"
-  rv=$?
-  if [[ $rv -eq 0 ]]; then
-    infoLog "$path backed-up to $OUTDIR"
-  else
-    errorLog "failed to backup $path (exit code $rv)"
-  fi
-done
+infoLog "backup completed: $SSH_HOST:$REMOTE_OUT"
 
-# Set output ownership and permissions
-chown -R "$CFG_USER":"$CFG_GROUP" "$OUTDIR"
-rv=$?
-if [[ $rv -ne 0 ]]; then
-  errorLog "failed to chown $OUTDIR (exit code $rv)"
-fi
-
-# Shrink the disk image
-$DIR/../lib/pishrink.sh "$OUTDIR/$OUTFILE"
-rv=$?
-if [[ $rv -ne 0 ]]; then
-  errorLog "failed to shrink $OUTDIR/$OUTFILE (exit code $rv)"
-fi
-
-
-semaphoreRelease "$LOCK"
 exit 0
+
+
+
